trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndCommit
  displayName: 'Build and Commit'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
      checkLatest: true

  # Step 1: Install dependencies and run build
  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

  # Step 2: Print the contents of package.json before prebuild
  - script: |
      echo "Contents of package.json before prebuild:"
      cat package.json
    displayName: 'Debug: Before Prebuild'

  # Step 3: Run prebuild
  - script: |
      npm version patch --no-git-tag-version
    displayName: 'npm version patch (prebuild)'

  # Step 4: Print the contents of package.json after prebuild
  - script: |
      echo "Contents of package.json after prebuild:"
      cat package.json
    displayName: 'Debug: After Prebuild'

  # Step 5: Check Git Status for Debugging
  - script: |
      git status
    displayName: 'Check Git Status'

  # Step 6: Commit changes if detected
  - script: |
      echo "Author: $(Build.SourceVersionAuthor)"
      author_email=$(git log -1 --format='%ae' $(Build.SourceVersion))
      echo "Author Email: $author_email"
      git config --global user.email "$author_email"
      git config --global user.name "$(Build.SourceVersionAuthor)"
      git add .
      if [ -n "$(git status --porcelain)" ]; then
        git commit -m "Bump version [skip ci]"
        git push origin HEAD:main
      else
        echo "No changes to commit."
      fi
    displayName: 'Commit and Push'
