trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    git config --global user.email "Manikkashyap@users.noreply.github.com"
    git config --global user.name "ManikKashyap"
    git fetch origin main:refs/remotes/origin/main
    git checkout -b main --track origin/main || git checkout main
    npm version patch
    git remote set-url origin https://username:TOKEN@github.com/Manikkashyap/angular_razorpay.git
    git push --follow-tags
  displayName: 'Update Version'

- script: |
    npm install
    npm run build -- --prod
  displayName: 'Build Angular App'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/dist'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/dist'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/dist'
    ArtifactName: 'drop'
    publishLocation: 'Container'
