trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndCommit
  displayName: 'Build and Commit'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
      checkLatest: true

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'dist'
      artifactName: 'drop'

  - script: |
      echo "Author: $(Build.SourceVersionAuthor)"
      echo "Author Email: $(Build.SourceVersionAuthorEmail)"
      git config --global user.email "$2"
      git config --global user.name "$1"
      git add .
      git commit -m "Bump version [skip ci]"
    displayName: 'Commit version bump'
    inputs:
      targetType: 'inline'
      script: |
        echo "Author: $1"
        echo "Author Email: $2"
        git config --global user.email "$2"
        git config --global user.name "$1"
        git add .
        git commit -m "Bump version [skip ci]"
      arguments: '$(Build.SourceVersionAuthor) "$(Build.SourceVersionAuthorEmail)"'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.SourcesDirectory)'
      artifactName: 'dist'
