trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:

- checkout: self
  persistCredentials: true   #Leave the OAuth token in the Git config in order to run git push commands in following powershell task

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- powershell: |
    echo $BUILD_REQUESTEDFOREMAIL
    git config --global user.email "$BUILD_REQUESTEDFOREMAIL"
    git config --global user.name "$BUILD_REQUESTEDFOR"
    # increment the patch version by 1
    # create a version commit and tag 
    # use [skip ci] in the commit message to skip from triggering the ci pipeline.
    npm version patch -f -m "bump version [skip ci]"
    # push back to azure git repo
    git push origin HEAD:$(Build.SourceBranchName) -q

- script: |
    npm install
    npm run build
  displayName: 'Build Angular App'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/dist'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/dist'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/dist'
    ArtifactName: 'drop'
    publishLocation: 'Container'
