trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  major: 1
  minor: 1

name: $(major).$(minor)$(Rev:.r)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js 18.x'

  - script: cat package.json
    displayName: 'Package.JSON before build'
  
  - script: |
      npm version $(major).$(minor)$(Rev:.r) --no-git-tag-version
    displayName: 'update version'

  - script: cat package.json
    displayName: 'Package.JSON after build'
