trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndCommit
  displayName: 'Build and Commit'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
      checkLatest: true

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'dist'
      artifactName: 'drop'

  - script: |
      echo "Author: $(Build.SourceVersionAuthor)"
      author_email=$(git log -1 --format='%ae' $(Build.SourceVersion))
      echo "Author Email: $author_email"
      git config --global user.email "$author_email"
      git config --global user.name "$(Build.SourceVersionAuthor)"
      git add .
      git commit -m "Bump version [skip ci]"
    displayName: 'Commit version bump'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.SourcesDirectory)'
      artifactName: 'dist'
