# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main  # Change this to your branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
    checkLatest: true

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'dist'  # Or wherever your build artifacts are
    artifactName: 'drop'

- script: |
    echo "Author: $(Build.SourceVersionAuthor)"
    echo "Author Email: $(Build.SourceVersionAuthorEmail)"
    git config --global user.email "$(Build.SourceVersionAuthorEmail)"
    git config --global user.name "$(Build.SourceVersionAuthor)"
    git add .
    git commit -m "Bump version [skip ci]"
  displayName: 'Commit version bump'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)'
    artifactName: 'dist'

