trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndCommit
  displayName: 'Build and Commit'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
      checkLatest: true

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'dist'
      artifactName: 'drop'

  - script: |
      echo "Author: $BUILD_SOURCEVERSIONAUTHOR"
      echo "Author Email: $BUILD_SOURCEVERSIONAUTHOREMAIL"
      git config --global user.email "$BUILD_SOURCEVERSIONAUTHOREMAIL"
      git config --global user.name "$BUILD_SOURCEVERSIONAUTHOR"
      git add .
      git commit -m "Bump version [skip ci]"
    env:
      BUILD_SOURCEVERSIONAUTHOR: $(Build.SourceVersionAuthor)
      BUILD_SOURCEVERSIONAUTHOREMAIL: $(Build.SourceVersionAuthorEmail)
    displayName: 'Commit version bump'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.SourcesDirectory)'
      artifactName: 'dist'
