trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  major: 1
  minor: 1
  appVersion: '$(major).$(minor).$(Rev:r)'

name: $(appVersion)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js 18.x'

  - script: cat package.json
    displayName: 'Package.JSON before build'

  - script: cat $(appVersion)
    displayName: 'App Version'

  - script: |
      npm version "$(Rev:r)" --no-git-tag-version
    displayName: 'npm install, update version, and build'

  - script: cat package.json
    displayName: 'Package.JSON after build'
